
services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=apiDB
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - D:\postgl_data\api_pgsql:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: signup_login_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db`:5432/apiDB
      db-username: root
      db-password: root
    depends_on:
      - db
    restart: always


